### ISSUE TITLE
upgrade to work with laravel 5.6

### ISSUE THREAD

**Issue by crissi** [jshannon63/laravel-psr15-middleware#6]
I am getting this error in Laravel 5.6:

Type error: Argument 1 passed to Symfony\\Component\\HttpFoundation\\Response::setCharset() must be of the type string, null given, called in /var/www/ordrestyring-api/vendor/jshannon63/laravel-psr15-middleware/src/Psr15MiddlewareDispatcher.php on line 58

**Comment by jshannon63** [comment]
v1.8 takes care of this issue.
